### Create user 1
POST http://localhost:3000/users
Content-Type: application/json

{
    "type": "common",
    "balance": 4000,
    "fullName": "Maria Silva",
    "cpf": "1234567890",
    "email": "maria@silva.com",
    "password": "123456"
}
###

### Create user 2
POST http://localhost:3000/users
Content-Type: application/json

{
  "type": "common",
  "balance": 14000,
  "fullName": "João Silva",
  "cpf": "1234567891",
  "email": "joao@silva.com",
  "password": "123456"
}
###

### Create user 3
POST http://localhost:3000/users
Content-Type: application/json

{
  "type": "store",
  "balance": 100,
  "fullName": "Ana Silva",
  "cpf": "1234567892",
  "email": "ana@silva.com",
  "password": "123456"
}
###

### List all users
GET http://localhost:3000/users
###

### Get user 1 balance
GET http://localhost:3000/users/balance/66a31256fd302846b0e7352f
###

### Transfer from user 1 to user 2 (success)
PATCH http://localhost:3000/users/transfer
Content-Type: application/json

{
  "value": 50.5,
  "payer": "66a31256fd302846b0e7352f",
  "payee": "66a3125efd302846b0e73530"
}
###

### Transfer from user 3 to user 1 (fail)
PATCH http://localhost:3000/users/transfer
Content-Type: application/json

{
  "value": 100.5,
  "payer": "66a31261fd302846b0e73531",
  "payee": "66a31256fd302846b0e7352f"
}
###

### Transfer from user 1 to user 3 (fail)
PATCH http://localhost:3000/users/transfer
Content-Type: application/json

{
  "value": 4050.6,
  "payer": "66a31256fd302846b0e7352f",
  "payee": "66a31261fd302846b0e73531"
}

### Get all users
GET http://localhost:3000/users
