version: '3.8'
services:
  mongo:
    container_name: mongo1
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  mongoCluster:
    external: true
    name: mongoCluster
