version: '3.8'
services:
  mongo:
    container_name: mongo1
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fintech
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --replSet myReplicaSet --bind_ip 127.0.0.1,mongo1
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly no
  api:
    image: node:18-alpine
    build:
      context: ./api
      dockerfile: api.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - mongo
      - redis
  redis-consumer:
    image: node:18
    build:
      context: ./redis-consumer
      dockerfile: redis.Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - mongo
      - redis
