version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - '5436:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresl/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
